
FIRSTNAME_MIN_LEGTH = 2
FIRSTNAME_MAX_LEGTH = 32

LASTNAME_MIN_LEGTH = 2
LASTNAME_MAX_LEGTH = 32

PASSWORD_MIN_LENGTH = 6
PASSWORD_MAX_LENGTH = 15
HASHED_PASSWORD_LENGTH = 255

SEX_LENGTH = 1

EMAIL_MIN_LEGNTH = 8
EMAIL_MAX_LENGTH = 255
