"""fk

Revision ID: 125218bea47b
Revises: 9cfd8a4e4b12
Create Date: 2023-03-31 11:28:01.377941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125218bea47b'
down_revision = '9cfd8a4e4b12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_email', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'notes', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'user_email')
    # ### end Alembic commands ###
