"""SUKA

Revision ID: 9cfd8a4e4b12
Revises: 32bb221e8be1
Create Date: 2023-03-28 17:49:57.563403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfd8a4e4b12'
down_revision = '32bb221e8be1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
